FROM debian

RUN apt-get update \
 && apt-get install -y software-properties-common \
    apt-transport-https \
    ca-certificates \
    curl \
    wget \
    gnupg2 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - \
  && apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
  && apt-get -y update && apt-get install -y vault=1.3.2 \
  && setcap cap_ipc_lock= /usr/bin/vault \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*