apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-sa-pass
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        resources:
          requests:
            {{- if .Values.requests }}
            memory: {{ .Values.requests.memory | default "500mi" | quote }}
            cpu: {{ .Values.requests.cpu | default "50m" | quote }}            
            {{- else }}
            memory: "500Mi"
            cpu: "50m"
            {{- end }}
          limits:
            {{- if .Values.limits }}
            memory: {{ .Values.limits.memory | default "2048Mi" | quote }}
            cpu: {{ .Values.limits.cpu | default "1000m" | quote }}
            {{- else }}
            memory: "2048Mi"
            cpu: "1000m"
            {{- end }}
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
