apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
     matchLabels:
       app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /html
          readOnly: true
          name: index-html
        - mountPath: /var/log/nginx
          name: log
        resources:
          requests:
            memory: 150Mi
            cpu: 25m
          limits:
            memory: 500Mi
            cpu: 200m
      volumes:
      - name: nginx-conf
        configMap:
          name: service-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: index-html
        configMap:
          name: service-conf
          items:
            - key: index.html
              path: index.html
      - name: log
        emptyDir: {}
      affinity:
        # the following defintion will make sure replicas of this deployment are placed on different nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}-app
              topologyKey: kubernetes.io/hostname
