global:
  name: consul
  datacenter: consul
  gossipEncryption:
    # Instructs Kubernetes to generate a gossip encryption key and register it as a Kubernetes secret.
    # Consul will use this key automatically at runtime.
    autoGenerate: true
  tls:
    # By enabling TLS and setting "enableAutoEncrypt" to true, the TLS system will configure itself.
    # We do not need to take any more action.
    enabled: true
    enableAutoEncrypt: true
    # The "verify" setting instructs Consul to verify the authenticity of servers and clients.
    verify: true
  acls:
    # By setting "manageSystemACLs" to true, the ACL system will configure itself. We do not need to take any other action.
    manageSystemACLs: true

client:
  enabled: true

server:
  replicas: 3
  storage: 10Gi  # Don't worry - this is max desired size as per docs. PV will be dynamically provisioned so actual size will be much smaller.

  # This is ONLY NEEDED for test/debug/troubleshoot purposes so we can get shell access to Consul server container as root
  securityContext:
    runAsNonRoot: false
    runAsUser: 0

connectInject:
  enabled: true
controller:
  enabled: true
  