apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storageSize | default "1Gi" | quote }} 
