apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: mssql-demo-deployment-manager

rules:
- nonResourceURLs: ['/api', '/healthz*']
  verbs: ['get', 'head']

- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "secrets", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]