kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mssql-demo-deployment-manager-binding-to-mssql-demo2
  namespace: mssql-demo2
subjects:
- kind: User
  name: "Boba Fett"
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: mssql-demo-deployment-manager
  apiGroup: ""