apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sys-fabrikam-pl-letsencrypt-staging
spec:
  acme:
    # The ACME STAGING server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: adam.demos@outlook.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: sys-fabrikam-pl-letsencrypt-staging
    solvers:
    - dns01:
        azureDNS:
          # AzureAD service principal appId
          clientID: d468859c-856a-408c-bd48-479cca0db56e
          # AzureAD service principal password has been stored in Kubernetes secret
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: azure-pass-sys-fabrikam-pl
            key: client-secret
          # Azure subscription id
          subscriptionID: dd54c00a-ece0-443a-b1fd-e149c305dd8d
          # AzureAD tenant id
          tenantID: 9116b818-f66e-46c4-be6b-79d931b8286b
          # Azure resource group where DNS Zone is crrated
          resourceGroupName: SysFabrikamPlRG
          # Azure DNS Zone name
          hostedZoneName: sys.fabrikam.pl
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud